#!/bin/bash
water="water"
stir="stir."
bestchol="bestchol"

to_decimal() {
    local val=$1 base=$2 result=0 len=${#1}
    for ((i=0; i<len; i++)); do
        char="${val:$i:1}"
        pos="${base%%$char*}"
        result=$((result * ${#base} + ${#pos}))
    done
    echo $result
}

from_decimal() {
    local num=$1 base=$2 result=""
    while [ $num -gt 0 ]; do
        result="${base:$((num % ${#base})):1}$result"
        num=$((num / ${#base}))
    done
    echo $result
}

w=$(to_decimal "$WATER" "$water")
s=$(to_decimal "$STIR" "$stir")
from_decimal $(( w + s )) "$bestchol"
